### ISSUE TITLE
Release 0.0.1

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-auth#10]
### Summary

Now that [conda 23.9.0](https://github.com/conda/conda/issues/13080) has been released, we can proceed with getting the initial release for conda-auth out 🚀. The first release for this project will be version `0.0.1` and is meant to express the very "alpha" nature of it.

These are the features we will be initially releasing:

- Support for HTTP Basic Authentication
- Addition of two new subcommands: `conda auth login` and `conda auth logout`
- Documentation website with an updated README
- Availability on conda-forge

### Linked Issues & PRs

- [x] https://github.com/conda-incubator/conda-auth/issues/5
- [x] https://github.com/conda-incubator/conda-auth/issues/2
- [x] https://github.com/conda-incubator/conda-auth/issues/6
- [x] #3

**Comment by travishathaway** [comment]
The last thing to do for this release is publishing it to conda-forge 🚀.

**Comment by travishathaway** [comment]
conda-forge feedstock pull request: https://github.com/conda-forge/staged-recipes/pull/24143
